#!/usr/bin/env bash
# installs nginx and redirects to video and custom 404
sudo apt-get -y update
sudo apt-get -y install nginx

file1="/usr/share/nginx/html/index.html"
file="/etc/nginx/sites-available/default"

# Correct the syntax to write "Hello World!" to the file
echo "Hello World!" | sudo tee "$file1" > /dev/null

sudo service nginx start

# Add the redirection configuration
phrase="location /redirect_me {\n  return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $phrase" "$file"

# Create and configure the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null
phrase2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n  root /usr/share/nginx/html;\n  internal;\n}\n"
sudo sed -i "30i $phrase2" "$file"

sudo service nginx restart
