#!/bin/bash

# Update package list
sudo apt update

# Install ufw if not already installed
sudo apt install ufw -y

# Allow incoming traffic on SSH, HTTPS, and HTTP ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw and reload the firewall
sudo ufw enable
sudo ufw reload
