#!/usr/bin/env bash
# run apache on designated container

FROM ubuntu:latest

# Install Apache
RUN apt-get update && apt-get install -y apache2

# Set Apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2

# Create a simple HTML file with "Hello Holberton"
RUN echo "Hello Holberton\n" > /var/www/html/index.html

# Expose port 80
EXPOSE 80

# Start Apache in the foreground
CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
