#!/usr/bin/env bash
# Generate a ssh key pair
# Set the filename for the private key
private_key="school"

# Set the number of bits for the key
key_bits=4096

# Set the passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f "$private_key" -N "$passphrase"

# Display information about the generated key pair
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $private_key.pub."
ssh-keygen -lf "$private_key"
